### ISSUE TITLE
Selection of mutiple contacts- Need help

### ISSUE THREAD

**Issue by iSachdeva** [CodeAtlas/VeeContactPicker#2]
How to select multiple contacts ?

**Comment by andreacipriani** [comment]
Hi @iSachdeva, at the moment is not possibile to select multiple contacts, but it might be a feature for the next version!

**Comment by ticatagdev** [comment]
Any news regarding implementation of this multiple contacts features ? would be very usefull because Apple did not fix the bug yes :(

**Comment by iSachdeva** [comment]
@ticatagdev  You can use this [THContactPicker on GitHub](https://github.com/tristanhimmelman/THContactPicker)

**Comment by andreacipriani** [comment]
I plan to work on it this weekend, I'll update you ASAP

**Comment by andreacipriani** [comment]
Hey, as promised I implemented the support for multiple contacts. Could you please try it out?
You can either clone the repo - checkout branch `v1` and include the files in your project -  or
include this version of the library in your Podfile:
pod 'VeeContactPicker', :git => 'https://github.com/CodeAtlas/VeeContactPicker.git', :branch => 'v1'

Please don't ship your app in prod with this version of the Pod. When is stable I'll do a new release of the Pod.
 
cc @iSachdeva @ticatagdev

**Comment by iSachdeva** [comment]
@andreacipriani  great, thanks.

**Comment by andreacipriani** [comment]
`v1` has been release with support for selecting multiple contacts
