### ISSUE TITLE
Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by irshadpc** [CodeAtlas/VeeContactPicker#5]
I got the this while using implementing the controller, and finally, my app crashed.

Here i got the logs 
Cannot find executable for CFBundle 0x101382580 </var/containers/Bundle/Application/4FFA28BA-874C-4E92-9A66-0831843BFB01/Test .app/Frameworks/VeeContactPicker.framework/VeeContactPicker.bundle> (not loaded)

**Comment by andreacipriani** [comment]
This should be solved in `v1`
